#! /usr/bin/env python3.2
import sys
import re
from xml.dom.minidom import parse, parseString

OK = 0
WA = 1
PE = 2
FL = 3

def main():
    if len(sys.argv) < 4:
        print("Usage: " + sys.argv[0] + "infile.txt outfile.txt answerfile.txt")
        sys.exit(1)

    ouxml = parse(sys.argv[2])
    anxml = parse(sys.argv[3])

    c1 = ouxml.toprettyxml()
    c2 = anxml.toprettyxml()
    c1 = re.sub(r'>\W+<', r'><', c1, flags=re.M)
    c2 = re.sub(r'>\W+<', r'><', c2, flags=re.M)
    if c1 == c2:
        sys.exit(OK)
    else:
        sys.exit(WA)

if __name__ == "__main__":
	    main()

# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
