#! /usr/bin/env python
import sys

OK = 0
WA = 1
PE = 2
FL = 3

def main():
    if len(sys.argv) < 4:
        print("Usage: " + sys.argv[0] + "infile.txt outfile.txt answerfile.txt")
        sys.exit(1)
    inf = open(sys.argv[1], 'r')
    ouf = open(sys.argv[2], 'r')
    ans = open(sys.argv[3], 'r')

    for inline in inf:
        outline = ouf.readline()
        ansline = ans.readline()
        answords = ansline.split()	
        outwords = outline.split()	
        if inline == ansline and outline == ansline:
            continue
        elif inline == ansline and outwords == answords:
            continue
        elif inline == ansline and outline != ansline:
            sys.exit(PE)
        else:
            if answords != outwords:
                sys.exit(WA)

    sys.exit(OK)

if __name__ == "__main__":
	    main()

# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
